<template>
    <v-row
    align="center"
    justify="center"
    >
        <v-col
        align="center"
        cols="12"
        sm="6"
        >
        <div
        class="pa-3"
        >
        <h2
        style="text-decoration: underline;"
        >
            Hobbys
        </h2>
    </div>

<div
class="pa-3"
>
    <div
    class="pa-3"
    >
        <v-img
        src="/world.png"
        height="175px"
        width="175px"
        >
        </v-img>
        <h3
        class="ma-2"
        >
            旅行
        </h3>
    </div>

    <div>
              <p>
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
      </p>
    </div>
</div>

<div
class="pa-3"
>
    <div
    class="pa-3"
    >
        <v-img
        src="/sado.png"
        height="175px"
        width="175px"
        >
        </v-img>
        <h3
        class="ma-2"
        >
            茶道
        </h3>
    </div>

    <div>
              <p>
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
      </p>
    </div>
</div>
        </v-col>
    </v-row>
</template>