<template>
    <v-row
    align="center"
    justify="center"
    >
        <v-col
        align="center"
        cols="12"
        sm="6"
        >
        <div
        class="pa-3"
        >
        <h2
        style="text-decoration: underline;"
        >
            Hobbys
        </h2>
    </div>

<div
class="pa-3"
>
    <div
    class="pa-3"
    >
        <v-img
        src="/world.png"
        height="175px"
        width="175px"
        >
        </v-img>
        <h3
        class="ma-2"
        >
            旅行
        </h3>
    </div>

    <div
    class="text-body-1"
    >
        これまで、タイ・マレーシア・韓国・ハワイ・グアムを旅しました。
        国内外問わず綺麗な景色を観たりその土地ならではの料理を食べるのが好きです。
        中でもタイのリペ島は別格です！
    </div>
</div>

<div
class="pa-3"
>
    <div
    class="pa-3"
    >
        <v-img
        src="/sado.png"
        height="175px"
        width="175px"
        >
        </v-img>
        <h3
        class="ma-2"
        >
            茶道
        </h3>
    </div>

    <div
    class="text-body-1"
    >
        2022年に入ってから習い始めました。
        「和菓子が好きだから！」というのもありますが、
        海外旅行に行った際に日本の魅力を伝えられる人でありたいと思っています。
    </div>
</div>
        </v-col>
    </v-row>
</template>