<template>
      <v-row
    align="center"
    justify="center"
    >
      <v-col
      cols="12"
      sm="6"
      align="center"
      >
        <div
        class="pa-3"
        >
    <h2
      style="text-decoration: underline;"
    >
      Skills
      </h2>
    </div>
    <div
    class="pa-3"
    >
      <v-img
      src="/skill-icon.png"
      width="145px"
      height="145px"
      >
      </v-img>
    </div>
    <div
    class="pa-3"
    >
      <p>
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
        texttexttexttexttext
      </p>
    </div>
          </v-col>
    </v-row>
</template>